### ISSUE TITLE
ClosestToNextInstanceHour Auto Scaling Instances Terminate Policy

### ISSUE THREAD

**Issue by taraslayshchuk** [awsdocs/amazon-ec2-auto-scaling-user-guide#14]
Could you please update [ClosestToNextInstanceHour](https://github.com/awsdocs/amazon-ec2-auto-scaling-user-guide/commit/541df1b43d7aaaf7b494405967d8b6dae9cac76d#diff-a5efbd10e398786ea8e6af7afbec361dR55) policy description, as  
> This policy helps you maximize the use of your instances and manage your Amazon EC2 usage costs.

Is not true information after [New – Per-Second Billing for EC2 Instances](https://aws.amazon.com/blogs/aws/new-per-second-billing-for-ec2-instances-and-ebs-volumes/) update.  
We don't need to terminate closest to the next billing hour instance to save bill.  
Same for default termination policy description: [1](https://github.com/awsdocs/amazon-ec2-auto-scaling-user-guide/commit/3a8910cb0b8e15c94fe7f264f440dda7d33f22c7#diff-a5efbd10e398786ea8e6af7afbec361dR39), [2](https://github.com/awsdocs/amazon-ec2-auto-scaling-user-guide/commit/3a8910cb0b8e15c94fe7f264f440dda7d33f22c7#diff-a5efbd10e398786ea8e6af7afbec361dR43)

**Comment by Reneehi** [comment]
Hi,

Thanks for your request. Per-second billing does not include all Linux distributions or Windows instances, so terminating the instance closest to the next billing hour can still help reduce costs when using an AMI that has an hourly charge. I will make this clearer in the section where we talk about customizing the termination policy. There is already a small reference in the Default Termination Policy section.

Renee
