### ISSUE TITLE
Auto Scaling Group with On-Demand and Spot Instances

### ISSUE THREAD

**Issue by anthonydurot** [awsdocs/amazon-ec2-auto-scaling-user-guide#16]
Hi everyone

In the [following documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/LaunchTemplates.html) it says that you can't create an ASG that launches both Spot and On-Demand Instances :
 
> For example, you cannot create an Auto Scaling group that launches both Spot and On-Demand Instances or that specifies multiple instance types. For more information, see Auto Scaling Groups with Multiple Instance Types and Purchase Options.

But on [this documentation](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-purchase-options.html) it says that you can create an ASG that scales both Spot and On-Demand Instances :

> You can launch and automatically scale a fleet of On-Demand Instances and Spot Instances within a single Auto Scaling group.

I think it's not really clear and I don't truly understand. I think the first quote is wrong because you can create an ASG that launches both Spot and On-Demand instances thanks to a Launch Template, am I wrong ?

Thank you !

**Comment by Reneehi** [comment]
Thank you for raising this issue. I'll fix this in the docs and then close this issue.
