### ISSUE TITLE
Activity History tab missing image

### ISSUE THREAD

**Issue by laboo** [awsdocs/amazon-ec2-auto-scaling-user-guide#4]
Shouldn't there be an image show the Activity History tab as it's described in the text? There's one for the Details tab, and one for the Instances tab. Confusing to me at first without the corresponding image for the Activity History tab.

**Comment by julieso** [comment]
Thanks for the suggestion. I will consider that next time I update screen shots in this guide. I notice that the screen shot of the Details tab is already out of date with the current UI.
