### ISSUE TITLE
Steps for creating auto scaling group fail

### ISSUE THREAD

**Issue by laboo** [awsdocs/amazon-ec2-auto-scaling-user-guide#6]
I followed the instructions for creating a ASG and it failed with a non-helpful error. Retrying didn't help.

![image](https://user-images.githubusercontent.com/424063/37920506-db171eda-30db-11e8-9c24-1ca1e126043f.png)

![image](https://user-images.githubusercontent.com/424063/37920578-1be1e530-30dc-11e8-8090-3976fdc738d8.png)

**Comment by laboo** [comment]
It did create the ASG, just can't retrieve the details. Seems like a bug in ASG. Not sure how to report that.

![image](https://user-images.githubusercontent.com/424063/37920779-9f67471a-30dc-11e8-82b0-2cf2fc19a0ee.png)

**Comment by laboo** [comment]
Launch template details:

![image](https://user-images.githubusercontent.com/424063/37921101-a80ad8e0-30dd-11e8-8d6b-f8a60b057f90.png)

**Comment by laboo** [comment]
No EC2 instances created.

**Comment by laboo** [comment]
Had similar problems doing it with a Launch Configuration (instead of a Launch Template). Creates the group, but spits out errors and doesn't launch any instances.

![image](https://user-images.githubusercontent.com/424063/37921946-0e7ad146-30e0-11e8-8b9b-f3f8c35567d0.png)

**Comment by julieso** [comment]
Thanks for reporting this. I will see what I can find out. Are you still getting an unknown error?

**Comment by julieso** [comment]
We tried to find your account to take a look, but couldn't locate it. This error can occur if you don't have permissions or if there is an issue with the console. What happens if you create the Auto Scaling group using the CLI?

**Comment by kisslaay** [comment]
Hey @julieso I am getting the same error. 

![image](https://user-images.githubusercontent.com/8381834/73738773-15246180-476b-11ea-98c3-66651c9e2369.png)

Please let me know what info you need or if you what me to try anything. I have not created ASG from CLI. 

Thanks in advance!

**Comment by Reneehi** [comment]
Hi @kisslaay 

If you can check your CloudTrail logs, and share whether there were any errors from around the same time, that would be helpful information. 

We might need to get some more information from you. Are you able to post this to the AWS discussion forum at https://forums.aws.amazon.com/forum.jspa?forumID=291? 

Renee
